[[random_responses]]
keyword = 'taiga'
messages = [
    '''Taiga? Yea, that's me.''',
    'What the actual fuck...',
    'Fine!',
    '''I don't have time for this.''',
    'Stop pinging me! <:TaigaPing:702686688589381732>',
    'Not my problem.',
    'Back off!',
    '''It's my Keitaro time right now so shut up.''',
    'Pffffft.',
    'Tch.',
    'Ugh... <:TaigaAnnoyed:702646568146436187>',
    '''Nice try. Didn't work.''',
    '''What's up, amateur?''',
    '''YOU'RE HOPELESS.''',
    'Lunch time.',
    '''That's my name, don't wear it out!''',
    '''Yeah, that's right!''',
    'Dummy...',
    'Come on, hurry up!',
    'What the actual fuck? <:TaigaAngry:699705315519889479>',
    '''Don't sweat it.''',
    '''Don't even think about it.''',
    'Later losers!',
    'Amateurs!',
    'I could do this all day with you <:TaigaGasm4:699708718446673960>',
]
reactions = [
    '<:TaigaKeitaroKiss2:699702364755460166>',
    '<:TaigaKeitaroKiss3:699711760243884153>',
    '<:TaigaKeitaroKissTop:700032178246910032>',
    '<:TaigaKeitaroKissBottom:700036884415643728>',
    '<:keitarocookie:699702884635246624>',
    '<:taigacookie:699702462918950992>',
    '<:TaigaMagic:700900603286781952>',
    '<:KeitaroMagic:700900563449282580>',
    '<:TaigaLOL:700004692079542333>',
    '<:chibitaiga:697893400891883531>',
    '<:TaigaFingerGunRight:702691649956085871>',
    '<:chibikeitaro:697905337495322632>',
    'ğŸˆ',
    'ğŸ±',
    'ğŸ”',
    'ğŸŸ',
    'ğŸ—',
    'ğŸ…',
    'ğŸ¯',
    'â˜€ï¸',
    'ğŸŒ',
    'â™‹',
    'ğŸ¦€',
    'ğŸ“•',
    'ğŸš',
]

[[random_responses]]
keyword = 'kou'
messages = [
    'My name is Minamoto Kou. Nice to meet you!',
    'What the...',
    'Alright.',
    '''Don't underestimate one of the Minamotos!''',
    '''Yes, Nene senpai? Oh, it's you...''',
    'I will never forgive Tsukasa!!!',
    '''Don't worry. I will purge this ultimate evil!''',
    'Release the seal on my rod already, Hanako!',
    '''I will always be Nene senpai's biggest alley!''',
    'Where is Mitsuba...',
    '''I hope next time I won't get turned into a doll again...''',
    'Take this!!!',
    '''I don't believe all apparitions are bad!''',
    '''I will watch Hanako and exorcise him myself when it's necessary, so let me do my job, Teru-nii!''',
    'No dessert for Teru-nii today.',
]
reactions = [
    '<:KouWorryBlush:705037055096389683>',
    '<:KouSugoi:705613007119450172>',
    '<:KouSpeechless:705037054878417036>',
    '<:KouSmilingSpeechlessHead:705037054454792214>',
    '<a:KouShook:705621519153233950>',
    '<:KouLookup:705054323473645659>',
    '<:KouLookdown:705054323553599508>',
    '<:KouHeh:712631800773738548>',
    '<a:KouFascinated:705279783340212265>',
    '<:KouCrack:705797095742767150>',
    '<:KouConfused:717495654003245076>',
    '<:KouConfident:705182851754360912>',
    '<:KouCatEars:705080422278627388>',
    '<:KouBakaNii:712631334937296946>',
    'ğŸŸ¨',
    'ğŸŸ¡',
    'ğŸ³',
    'ğŸš',
    'ğŸ—',
    'ğŸ¥˜',
    'ğŸ›',
    'ğŸœ',
    'ğŸ²',
    'ğŸ§Ÿ',
    'ğŸ‘»',
    'ğŸ˜ˆ',
    'ğŸ‘º',
    'ğŸ‘¹',
    'ğŸ‰‘',
    'ğŸƒ',
]

[[random_responses]]
keyword = 'hiro'
messages = [
    'Gotta admit. Sometimes I do feel bad for Hiro.',
    '''Well, it's not really my problem that Keitaro likes me more, huh?''',
    'I hope Hiro can get his right one soon.',
    'Now can he even make a burger? I wonder...',
    'Anyway, Hiro will be terribly wrong if he thinks he can steal Keitaro from me!',
    '''I'm the best! Except for cooking...''',
    '''Jeez, sometimes Keitaro just can't stop talking about Hiro's cooking.''',
    'Well, those tamagoyaki sure is amazing.',
    'Maybe I should start learning cooking as well so Keitaro will have no reason to complain about me.',
    'I swear Hiro dyed his hair back only because he wants to steal Keitaro from me! <:TaigaAngry:699705315519889479>',
    'Due to unforeseen circumstances, Hiro route will be removed from the game.',
]
reactions = [
    'ğŸ³',
    'ğŸš',
    'ğŸ‘¨â€ğŸ³',
    'ğŸ¥š',
    'ğŸ®',
    'ğŸ•¹ï¸',
    'ğŸ¥˜',
    'ğŸ›',
    'ğŸ¤¤',
    'ğŸœ',
    'ğŸ¥”',
    'ğŸ¥¢',
    'ğŸ¥„',
    'ğŸ²',
    'ğŸ˜‹',
    'ğŸ¥¡',
    'ğŸ§Ÿ',
    'ğŸ˜±',
    'ğŸ‘»',
    'âœŠ',
    'ğŸ¤¡',
]

[[random_responses]]
keyword = 'keitaro'
messages = [
    '''What's your problem with my boyfriend?''',
    'Stop fooling around and come to me.',
    'I really hope we can live together.',
]
reactions = [
    '<:TaigaKeitaroKiss2:699702364755460166>',
    '<:TaigaKeitaroKiss3:699711760243884153>',
    '<:TaigaKeitaroKissTop:700032178246910032>',
    '<:TaigaKeitaroKissBottom:700036884415643728>',
    'ğŸ’—',
    'ğŸ’“',
    'ğŸ’˜',
    'ğŸ’•',
    'â¤ï¸',
    '<:keitarocookie:699702884635246624>',
    '<:taigacookie:699702462918950992>',
    '<:TaigaMagic:700900603286781952>',
    '<:KeitaroMagic:700900563449282580>',
    '<:TaigaLOL:700004692079542333>',
    '<:chibitaiga:697893400891883531>',
    '<:TaigaFingerGunRight:702691649956085871>',
    '<:chibikeitaro:697905337495322632>',
    'âœï¸',
    'ğŸ“·',
    'ğŸ“¸',
    'ğŸ˜',
    'ğŸ“—',
    'ğŸ¸',
    'ğŸŒ§ï¸',
    'â˜‚ï¸',
    'â™ˆ',
    'ğŸ',
]

[[random_responses]]
keyword = 'natsumi'
messages = ['''<:TaigaSmug:702210822310723614> I'm still better than him 'cause I'm the best!''']
reactions = [
    'ğŸŠâ€â™‚ï¸',
    'ğŸ§¹',
    'ğŸ',
    'âŒš',
    '<:chibinatsumi:697893038936293416>',
    'â™Š',
]

[[random_responses]]
keyword = 'hunter'
messages = [
    '''<:KachiSad:701226059726585866> I felt him. I'd be baffled if someone told me to stop handcrafting. I mean how else could I make a bracelet?''',
    '''You're just like Keitaro. You really need to learn how to say no.''',
]
reactions = [
    'âœï¸',
    'ğŸ–ï¸',
    'ğŸ¨',
    'ğŸ–Œï¸',
    'ğŸ‡',
    'â™“',
    'ğŸŸ',
    '<:chibihunter:697892978718670898>',
]

[[random_responses]]
keyword = 'yoichi'
messages = [
    '<:TaigaSmug:702210822310723614> *Not my type.*',
    'You stink.',
    'Do I really have to drag you to the bathroom to make you take a bath?',
    'That collar is ridiculous. Thankfully I have a better present for Keitaro in my route.',
    '''I don't think Hiro will easily go out with you even though Keitaro is already mine.''',
]
reactions = [
    'ğŸº',
    'ğŸ•',
    'ğŸ¶',
    'ğŸ¾',
    'ğŸ’©',
    'ğŸ¦´',
    '<:Spray:701105694761418774>',
    '<:TaigaSmug:702210822310723614>',
    'â™’',
    '<:chibiyoichi:697893116253831229>',
    'ğŸ¬',
    'ğŸ¥',
    'ğŸ¦',
    'ğŸ¿',
    'ğŸ“½ï¸',
    'ğŸ“º',
    'ğŸ’¢',
    'ğŸš',
]

[[random_responses]]
keyword = 'yoshi'
messages = ['''<:TaigaAngry:699705315519889479> Stop sticking your nose where it doesn't belong!''']
reactions = [
    '<:TaigaClimb:699710154861445172>',
    '<:Spray:701105694761418774>',
    '<:TaigaAngry:699705315519889479>',
    '<:TaigaAnnoyed:702646568146436187>',
    '<:TaigaUneasy2:700006812673638500>',
    'ğŸ»',
    'â™“',
    'ğŸŸ',
    'ğŸ’¢',
    'ğŸ¸',
    'ğŸ•ï¸',
    'â›º',
    'ğŸ”¥',
]

[[random_responses]]
keyword = 'yuri'
messages = ['''<:TaigaAck2:700006264507465778> Get away from us! Although you're not wrong at all...''']
reactions = [
    '<:TaigaClimb:699710154861445172>',
    '<:Spray:701105694761418774>',
    '<:TaigaAngry:699705315519889479>',
    '<:TaigaAnnoyed:702646568146436187>',
    '<:TaigaUneasy2:700006812673638500>',
    'ğŸ¤®',
    'ğŸ¤¢',
    'ğŸ¦‹',
    'â™‰',
    'ğŸ„',
    'ğŸ’¢',
]

[[random_responses]]
keyword = 'goro'
messages = ['So when are you going to confess to Yoshi?']
reactions = [
    '<:TaigaAck2:700006264507465778>',
    '<:TaigaUneasy2:700006812673638500>',
    'ğŸ¼',
    'â™‹',
    'ğŸ¦€',
    'ğŸ¥¾',
]

[[random_responses]]
keyword = 'eduard'
messages = [
    'Your sassiness is killing me, Eduard.',
    'Where is the wax your promised me?',
    '''I don't know which is crazier, his cheesy talk or his sassiness...''',
]
reactions = [
    '<:Spray:701105694761418774>',
    '<:TaigaAngry:699705315519889479>',
    '<:TaigaAnnoyed:702646568146436187>',
    '<:chibieduard:697892864725614592>',
    'ğŸ’…',
    'ğŸ¦©',
    'ğŸ’‡â€â™‚ï¸',
    'ğŸ™',
    'ğŸ¦‘',
    'ğŸ‘¾',
    'â™Š',
]

[[random_responses]]
keyword = 'lee'
messages = ['Next time you talk, at least bring me a dictionary, Lee.']
reactions = [
    'ğŸ“š',
    'ğŸ’»',
    '<:chibilee:697892809600008253>',
    'ğŸ',
    'â™Œ',
]

[[random_responses]]
keyword = 'seto'
messages = ['''No thanks. I don't really play PnesP games.''']
reactions = [
    'ğŸ’»',
    'ğŸˆ',
    'ğŸ±',
    'ğŸµ',
    'ğŸ§',
    'ğŸŠâ€â™‚ï¸',
    'ğŸ¤',
    'â™Œ',
]

[[random_responses]]
keyword = 'felix'
messages = ['Ri$h']
reactions = [
    'ğŸ¦Š',
    'ğŸ’²',
    'ğŸ’°',
    'ğŸ’±',
    'ğŸ’',
    'ğŸ’',
    'â™',
]

[[random_responses]]
keyword = 'yuki'
messages = ['KEEP THAT DAMN DOG AWAY FROM ME!!!']
reactions = ['ğŸ•']

[[random_responses]]
keyword = 'kieran'
messages = ['I hope for the best for him...']
reactions = [
    'ğŸ¦',
    'â™Œ',
    '<:chibikieran:697905134306328737>',
    '<:KieranMask:700003622183895099>',
    '<:KieranHate:707314324812595202>',
]
